[build]
  command = "npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  external_node_modules = ["@react-router/node", "isbot"]
  # Include the React Router server build in the function bundle
  included_files = ["build/server/**"]

# Static assets should be served directly (higher priority)
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/*.png"
  to = "/:splat.png"
  status = 200

[[redirects]]
  from = "/*.jpg"
  to = "/:splat.jpg"
  status = 200

[[redirects]]
  from = "/*.svg"
  to = "/:splat.svg"
  status = 200

# React Router v7 with Node.js runtime - route everything through server function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = false

# Headers for security and caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # SEO-friendly headers
    X-Robots-Tag = "index, follow"

# Special handling for robots.txt and sitemap.xml
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200